### ISSUE TITLE
Comments are not editable by author

### ISSUE THREAD

**Issue by pkopac** [pirati-cz/issue-tracker#5]

**Comment by scippio** [comment]
To je otázka zda to dělat... chápu, že se to hodí, když se někdo "přepíše" a potřebuje to opravit... možná bych tam mohl udělat to, že po určitou dobu lze komentář smazat.. třeba 15-30 nebo 60 minut...

PS: (nepíšu jsem anglicky, protože to tu stejně všechno zatím dělám česky :) )

**Comment by pkopac** [comment]
If you don't mind, pls use English, because in near future, foreign developers might join. Thx.

I'd recommed using wiki history for editing comments, if it's possible. So that we can see anyway, what was edited and what deleted.
