### ISSUE TITLE
Volunteer groups should be hierarchical

### ISSUE THREAD

**Issue by pkopac** [pirati-cz/issue-tracker#6]
For example, instead of having these groups:
"Language - English - B1,B2"
"Programming - Java - SE"
There should be hierarchy of
Language -> English -> B1,B2
Programming -> Java -> SE

**Comment by scippio** [comment]
Nejdřív jsem to chtěl dělat a potom jsem si řekl, že to nebudu komplikovat... ale zase když tam teď vidím více skupin, tak mi to stromové rozklikávací členění přijde zase ok... takže to tam asi udělám :)

**Comment by pkopac** [comment]
Well, can I ask you
a) why do you speak Czech?
b) when will you upload the code, so that WE can program the features? I DON'T want YOU to implement it. I want YOU to UPLOAD the source code.
Thank you
